name: Label Checker
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
jobs:
  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - uses: docker://agilepathway/pull-request-label-checker:latest@sha256:65e57fd98ba3ab6ca4fcbc5a0aef288dd984ee4ab988f124d83424d19b55b801
        with:
          one_of: bug,feature,enhancement,documentation,dependencies,ignore-for-release,ci/cd
          repo_token: ${{ secrets.GITHUB_TOKEN }}
